export const iconName: any = {
  urban: "urban",
  tribe: "tribe",
  family: "family",
  location: "location",
  bedroom: "bedroom",
  pool: "pool",
  food: "food",
  wifi: "wifi",
  spa: "spa",
  games: "games",
  coworking: "coworking",
  bar: "bar",
  nomad: "nomad",
  divisor: "divisor",
  instagram: "instagram",
  facebook: "facebook",
  twitter: "twitter",
  youtube: "youtube",
  list: "list",
  calendar: "calendar",
};
